// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BookingSystem.proto

package grpc.ca.Booking;

public interface HelloRequest1OrBuilder extends
    // @@protoc_insertion_point(interface_extends:HelloRequest1)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name1 = 1;</code>
   */
  java.lang.String getName1();
  /**
   * <code>string name1 = 1;</code>
   */
  com.google.protobuf.ByteString
      getName1Bytes();
}
