// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BookingSystem.proto

package grpc.ca.Booking;

public interface HelloReply2OrBuilder extends
    // @@protoc_insertion_point(interface_extends:HelloReply2)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message2 = 1;</code>
   */
  java.lang.String getMessage2();
  /**
   * <code>string message2 = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessage2Bytes();
}
