// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BookingSystem.proto

package grpc.ca.Booking;

public interface HelloReply1OrBuilder extends
    // @@protoc_insertion_point(interface_extends:HelloReply1)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message1 = 1;</code>
   */
  java.lang.String getMessage1();
  /**
   * <code>string message1 = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessage1Bytes();
}
