// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BookingSystem.proto

package grpc.ca.Booking;

public interface HelloRequest2OrBuilder extends
    // @@protoc_insertion_point(interface_extends:HelloRequest2)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name2 = 1;</code>
   */
  java.lang.String getName2();
  /**
   * <code>string name2 = 1;</code>
   */
  com.google.protobuf.ByteString
      getName2Bytes();
}
