// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BookingSystem.proto

package grpc.ca.Booking;

public final class NewServiceImpl1 {
  private NewServiceImpl1() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HelloRequest1_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HelloRequest1_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HelloReply1_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HelloReply1_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HelloRequest2_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HelloRequest2_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HelloReply2_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HelloReply2_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023BookingSystem.proto\"\036\n\rHelloRequest1\022\r" +
      "\n\005name1\030\001 \001(\t\"\037\n\013HelloReply1\022\020\n\010message1" +
      "\030\001 \001(\t\"\036\n\rHelloRequest2\022\r\n\005name2\030\001 \001(\t\"\037" +
      "\n\013HelloReply2\022\020\n\010message2\030\001 \001(\t2w\n\rBooki" +
      "ngSystem\022,\n\nGetBooking\022\016.HelloRequest1\032\014" +
      ".HelloReply1\"\000\0228\n\024GetBookingThirdParty\022\016" +
      ".HelloRequest2\032\014.HelloReply2\"\0000\001B$\n\017grpc" +
      ".ca.BookingB\017NewServiceImpl1P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_HelloRequest1_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_HelloRequest1_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HelloRequest1_descriptor,
        new java.lang.String[] { "Name1", });
    internal_static_HelloReply1_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_HelloReply1_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HelloReply1_descriptor,
        new java.lang.String[] { "Message1", });
    internal_static_HelloRequest2_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_HelloRequest2_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HelloRequest2_descriptor,
        new java.lang.String[] { "Name2", });
    internal_static_HelloReply2_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_HelloReply2_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HelloReply2_descriptor,
        new java.lang.String[] { "Message2", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
